name: OpenLark Bot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run syntax check
      run: |
        python -m py_compile feishu_bot.py
        python -m py_compile sdk_connect.py
        python -m py_compile user_manager.py

    - name: Verify environment setup
      run: |
        # 创建测试用的环境变量文件
        cat > .env.test << 'EOF'
        FEISHU_APP_ID=test_app_id
        FEISHU_APP_SECRET=test_app_secret
        FEISHU_VERIFICATION_TOKEN=test_verification_token
        FEISHU_ENCRYPT_KEY=test_encrypt_key
        COMPANY_ID=12345
        EOF
        
        # 测试环境变量加载
        python -c "
        from dotenv import load_dotenv
        import os
        load_dotenv('.env.test')
        print('环境变量加载成功')
        print('COMPANY_ID:', os.getenv('COMPANY_ID'))
        "

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        # 创建部署包
        mkdir -p deployment
        cp -r *.py data deployment/
        cp requirements.txt deployment/
        cp .env.example deployment/.env.example
        
        # 创建部署说明
        cat > deployment/README.md << 'EOF'
        # OpenLark Bot 部署包
        
        ## 快速开始
        
        1. 安装依赖: pip install -r requirements.txt
        2. 配置环境变量: cp .env.example .env 并编辑
        3. 启动服务: python sdk_connect.py
        
        ## 环境变量说明
        
        请参考项目根目录的 README.md 文件
        EOF
        
        # 打包
        tar -czf openlark-bot-deployment.tar.gz deployment/

    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: openlark-bot-deployment
        path: openlark-bot-deployment.tar.gz

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openlark-bot-deployment.tar.gz
        generate_release_notes: true
